spring:
    application:
      name: member
eureka:
    client:
      service-url:    #\u591A\u4E2Aeureka\u670D\u52A1\u4E4B\u95F4\u4E92\u76F8\u8C03\u7528(\u96C6\u7FA4)
       defaultZone: http://localhost:8000/eureka/  #,http://localhost:9000/eureka/  #,http://localhost:8763/eureka/

server:
  port: 8001
  enable-self-preservation: false #关闭Eureka自我保护
##swagger扫包范围
swagger:
  base-package: com.yzj.api.member
