spring:
    application:
      name: euraka
eureka:
    client:
      service-url:    #\u591A\u4E2Aeureka\u670D\u52A1\u4E4B\u95F4\u4E92\u76F8\u8C03\u7528(\u96C6\u7FA4)
       defaultZone: http://localhost:8000/eureka/  #,http://localhost:9000/eureka/  #,http://localhost:8763/eureka/
    register-with-eureka: false

server:
  port: 8000
  enable-self-preservation: false  #\u5173\u95ED\u81EA\u6211\u4FDD\u62A4\u673A\u5236
